### ISSUE TITLE
Multi-host throwing System.Collections.Generic.KeyNotFoundException: The given key (TypesToScan) was not present in the dictionary. 

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Host.AzureCloudService#30]
As part of the [smoke testing of multi-host sample](https://github.com/Particular/docs.particular.net/pull/1384#issuecomment-206175941), have ran into this issue.

Host is failing with the following exception (hidden by cloud service):

```
[fabric] Role Instance: deployment27(257).HostCloudService.HostWorker.0
[fabric] Role state Busy
[runtime] Role entrypoint . CALLING   OnStart(): WorkerRole
[runtime] System.Collections.Generic.KeyNotFoundException: The given key (TypesToScan) was not present in the dictionary.
   at NServiceBus.Settings.SettingsHolder.Get(String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 95
   at NServiceBus.Settings.SettingsHolder.Get[T](String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 21
   at NServiceBus.SettingsExtentions.GetConfigSection[T](ReadOnlySettings settings) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\SettingsExtentions.cs:line 20
   at NServiceBus.Hosting.Azure.DynamicHostController.Start() in C:\BuildAgent\work\79b79bd92dd94994\src\NServiceBus.Hosting.Azure\DynamicHost\DynamicHostController.cs:line 24
   at WorkerRole.OnStart() in C:\GitHub\nsb\docs.particular.net\samples\azure\shared-host\Version_6\HostWorker\WorkerRole.cs:line 12
   at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum)
   at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.<InitializeRole>b__0()
[runtime] Unhandled Exception:
System.Collections.Generic.KeyNotFoundException: The given key (TypesToScan) was not present in the dictionary.
   at NServiceBus.Settings.SettingsHolder.Get(String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 95
   at NServiceBus.Settings.SettingsHolder.Get[T](String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 21
   at NServiceBus.SettingsExtentions.GetConfigSection[T](ReadOnlySettings settings) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\SettingsExtentions.cs:line 20
   at NServiceBus.Hosting.Azure.DynamicHostController.Start() in C:\BuildAgent\work\79b79bd92dd94994\src\NServiceBus.Hosting.Azure\DynamicHost\DynamicHostController.cs:line 24
   at WorkerRole.OnStart() in C:\GitHub\nsb\docs.particular.net\samples\azure\shared-host\Version_6\HostWorker\WorkerRole.cs:line 12
   at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum)
   at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.<InitializeRole>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Unhandled exception occured: System.Collections.Generic.KeyNotFoundException: The given key (TypesToScan) was not present in the dictionary.
   at NServiceBus.Settings.SettingsHolder.Get(String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 95
   at NServiceBus.Settings.SettingsHolder.Get[T](String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 21
   at NServiceBus.SettingsExtentions.GetConfigSection[T](ReadOnlySettings settings) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\SettingsExtentions.cs:line 20
   at NServiceBus.Hosting.Azure.DynamicHostController.Start() in C:\BuildAgent\work\79b79bd92dd94994\src\NServiceBus.Hosting.Azure\DynamicHost\DynamicHostController.cs:line 24
   at WorkerRole.OnStart() in C:\GitHub\nsb\docs.particular.net\samples\azure\shared-host\Version_6\HostWorker\WorkerRole.cs:line 12
   at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum)
   at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.<InitializeRole>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by SeanFeldman** [comment]
Not relevant any more.
